// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARmk-WvgTB6pj4uyVqNs9wBmaDH6lO554',
    appId: '1:563135105543:web:0d3d07aac26107009438a2',
    messagingSenderId: '563135105543',
    projectId: 'delivery-egas',
    authDomain: 'delivery-egas.firebaseapp.com',
    storageBucket: 'delivery-egas.appspot.com',
    measurementId: 'G-LD0YF35L4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbknXbsnNuug4ERHJ4cdkLvA9PQFeNN60',
    appId: '1:563135105543:android:604bdbc8b03db3f69438a2',
    messagingSenderId: '563135105543',
    projectId: 'delivery-egas',
    storageBucket: 'delivery-egas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbZzSt_vI6RLyyeKfgTarSYm1SHveTPOM',
    appId: '1:563135105543:ios:e3bad581295a0f199438a2',
    messagingSenderId: '563135105543',
    projectId: 'delivery-egas',
    storageBucket: 'delivery-egas.appspot.com',
    iosClientId: '563135105543-cbc3eio9httf7u3c5oiftf739vad9npm.apps.googleusercontent.com',
    iosBundleId: 'com.cuteweb.egasdelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbZzSt_vI6RLyyeKfgTarSYm1SHveTPOM',
    appId: '1:563135105543:ios:e3bad581295a0f199438a2',
    messagingSenderId: '563135105543',
    projectId: 'delivery-egas',
    storageBucket: 'delivery-egas.appspot.com',
    iosClientId: '563135105543-cbc3eio9httf7u3c5oiftf739vad9npm.apps.googleusercontent.com',
    iosBundleId: 'com.cuteweb.egasdelivery',
  );
}
